#image: python:3.5
#image: mlp6/fem
image: continuumio/anaconda3

test:
    script: 
    #- pip install -r requirements.txt  
    - conda install -y pytest-cov
    - export PYTHONPATH=../
    - py.test -v --cov
